SELECT * FROM employees WHERE salary BETWEEN 10000 AND 14000;
SELECT * FROM employees WHERE hire_date BETWEEN '07-JUN-02' AND '29-JAN-08';
SELECT * FROM employees WHERE hire_date BETWEEN '07-JUN-02' AND '29-JAN-05';
SELECT * FROM employees WHERE hire_date NOT BETWEEN '07-JUN-02' AND '29-JAN-05';
SELECT * FROM employees WHERE hire_date NOT BETWEEN '07-JUN-02' AND '29-JAN-08';
SELECT * FROM employees WHERE hire_date BETWEEN '07-JUN-02' AND SYSDATE;
SELECT * FROM employees WHERE hire_date NOT BETWEEN '07-JUN-02' AND SYSD
ATE;ATE;
SELECT * FROM employees WHERE hire_date BETWEEN SYSDATE-365 AND SYSDATE;    
SELECT * FROM employees WHERE hire_date NOT BETWEEN SYSDATE-365 AND SYSDATE;
SELECT * FROM employees WHERE hire_date BETWEEN SYSDATE-365*2 AND SYSDATE-365;
SELECT * FROM employees WHERE hire_date NOT BETWEEN SYSDATE-365*2 AND SYSDATE-365;
SELECT * FROM employees WHERE hire_date BETWEEN SYSDATE-365*3 AND SYSDATE-365*2;
SELECT * FROM employees WHERE hire_date NOT BETWEEN SYSDATE-365*3 AND SYSDATE-365*2;
SELECT * FROM employees WHERE hire_date BETWEEN SYSDATE-365*4 AND SYSDATE-365*3;
SELECT * FROM employees WHERE hire_date NOT BETWEEN SYSDATE-365*4 AND SYSDATE-365*3;
SELECT * FROM employees WHERE hire_date BETWEEN SYSDATE-365*5 AND SYSDATE-365*4;
SELECT * FROM employees WHERE hire_date NOT BETWEEN SYSDATE-365*5 AND SYSDATE-365*4;
SELECT * FROM employees WHERE hire_date BETWEEN SYSDATE-365*6 AND SYSDATE-365*5;
SELECT * FROM employees WHERE hire_date NOT BETWEEN SYSDATE-365*6 AND SYSDATE-365*5;


